# Configuration of your Digitalstrom server
server:
  # Server address
  address: https://127.0.0.1:8080
  # Valid login token
  logintoken: d1308cb...
  # Number of second to wait between polling of events
  waitpolling: 10

log:
  # one of panic|fatal|error|warn|info|debug|trace
  # check https://github.com/sirupsen/logrus
  level: info